wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.29
    code_path: code/deeptricks/callbacks/__init__.py
    framework: tensorflow
    is_jupyter_run: false
    python_version: 3.6.8
